# fly.toml app configuration file generated for pbjellyjams on 2024-08-19T19:33:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pbjellyjams'
primary_region = 'ewr'

[build]
  [build.args]
    GO_VERSION = '1.22.0'

[env]
  PORT = '6969'

[http_service]
  internal_port = 6969
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/assets'
  url_prefix = '/assets'
